# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com

# The lines below are called `modelines`. See `:help modeline`
# Feel free to remove those if you don't want/need to use them.
# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: mkcd
    main: ./main.go
    binary: mkcd
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}
    flags:
      - -trimpath

archives:
  - formats: [tar.gz]
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        formats: [zip]

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

# Code signing for macOS
# Set APPLE_CERTIFICATE environment variable with your certificate name
# Example: export APPLE_CERTIFICATE="Developer ID Application: Your Name (TEAM_ID)"
signs:
  - artifacts: binary
    ids:
      - mkcd
    cmd: codesign
    args:
      - "--force"
      - "--deep"
      - "--sign"
      - "${APPLE_CERTIFICATE}"
      - "${artifact}"
    env:
      - APPLE_CERTIFICATE

# Alternative: Basic notarization setup (optional - requires Apple Developer account)
# Uncomment and configure if you have notarization credentials
# notarizations:
#   - artifacts: archive
#     id: default
#     provider: apple
#     certificate: "${APPLE_CERTIFICATE}"
#     username: "${APPLE_USERNAME}"
#     password: "${APPLE_PASSWORD}"
#     team_id: "${APPLE_TEAM_ID}"

release:
  github:
    owner: Narven
    name: mkcd
  mode: replace
  footer: >-

    ---

    Released by [GoReleaser](https://github.com/goreleaser/goreleaser).
